<a href="https://colab.research.google.com/github/vamshidhar23/2303A510H7-PYHTON-FOR-DATA-SCIENCE/blob/main/LAB_3_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

A = np.random.randint(1, 11, size=(3, 3))
B = np.random.randint(1, 11, size=(3, 3))

print("Matrix A:\n", A)
print("Matrix B:\n", B)

add_result = np.add(A, B)
sub_result = np.subtract(A, B)

print("\nMatrix Addition (A + B):\n", add_result)
print("\nMatrix Subtraction (A - B):\n", sub_result)

row, col = 1, 2
manual_add = A[row, col] + B[row, col]
manual_sub = A[row, col] - B[row, col]

print(f"\nManual check at position (row={row+1}, col={col+1}):")
print(f"A[{row},{col}] = {A[row, col]}, B[{row},{col}] = {B[row, col]}")
print(f"A+B at that position = {manual_add}, np.add result = {add_result[row, col]}")
print(f"A-B at that position = {manual_sub}, np.subtract result = {sub_result[row, col]}")

print("\nNote: Broadcasting is NOT used here because both matrices have the same shape (3x3).")


Matrix A:
 [[ 9  2  6]
 [10  9 10]
 [ 5  4  1]]
Matrix B:
 [[4 6 1]
 [3 4 9]
 [2 4 4]]

Matrix Addition (A + B):
 [[13  8  7]
 [13 13 19]
 [ 7  8  5]]

Matrix Subtraction (A - B):
 [[ 5 -4  5]
 [ 7  5  1]
 [ 3  0 -3]]

Manual check at position (row=2, col=3):
A[1,2] = 10, B[1,2] = 9
A+B at that position = 19, np.add result = 19
A-B at that position = 1, np.subtract result = 1

Note: Broadcasting is NOT used here because both matrices have the same shape (3x3).


In [ ]:
import numpy as np
np.random.seed(0)
matrix_a = np.random.randint(0, 10, size=(3, 2))
matrix_b = np.random.randint(0, 10, size=(2, 3))
matrix_product = np.dot(matrix_a, matrix_b)
display(matrix_a)
display(matrix_b)
display(matrix_product)

array([[5, 0],
       [3, 3],
       [7, 9]])

array([[3, 5, 2],
       [4, 7, 6]])

array([[15, 25, 10],
       [21, 36, 24],
       [57, 98, 68]])